openapi: 3.0.3
info:
  title: UniversalBlogger REST API
  description: UniversalBlogger REST API. This meant to be the only interface to the backing database. All data is retrieved and entered here.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  
