services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:latest
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
    - 9200:9200
    - 9300:9300
    networks:
      - somenetwork

  kibana:
    container_name: kibana
    image: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    networks:
      - somenetwork
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  somenetwork:
    driver: bridge
